#pragma config(Sensor, S1,     ColorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     USonicSensor,   sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          lWheel,        tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          rWheel,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	long redValue;
	long greenValue;
	long blueValue;

	//Keep looping forever
	while(true)
	{
		//If the color sensor senses the line (a dark value
		//lower than the calculated threshold of 50):

		getColorRGB(ColorSensor, redValue, greenValue, blueValue);
		displayStringAt(3,20, "red: %d",redValue);
		displayStringAt(4,40, "green: %d",greenValue);
		displayStringAt(5,60, "blue: %d",blueValue);
		displayStringAt(6, 80, "distance: %d", getUSDistance(USonicSensor));
		
		//white/table
		if (blueValue >= 53 && blueValue <= 57 && greenValue >= 60 && greenValue <= 64 && redValue >= 48 && redValue <= 52) {
			//turn left
			setMotorSpeed(lWheel, 0);
			setMotorSpeed(rWheel, 10);
			}
		
		//blue
		if (blueValue >= 18 && blueValue <= 20 && greenValue >= 12 && greenValue <= 13 && redValue >= 60 && redValue <= 100) {
			//straight
				setMotorSpeed(lWheel, 10);
				setMotorSpeed(rWheel, 10);
				}
				
		//turn right
		else if (redValue <= 50) {
			setMotorSpeed(lWheel, 10);
			setMotorSpeed(rWheel, 0);	
			}
		}
}
