#pragma config(Sensor, S1,     ColorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     USonicSensor,   sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          lWheel,        tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          rWheel,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// initialization

const int topSpeed = 10;
	
float distance;

void greenAction();
void blueAction();

void greenAction() {
	
}

task main()
{
	// initialize light and get initial intensity values
	sleep(2000);
	getColorRGB(ColorSensor, initRed, initGreen, initBlue);
	initIntens = (initRed + initBlue + initGreen) / 3;

	//Keep looping forever
	while(true)
	{
		getColorRGB(ColorSensor, redValue, greenValue, blueValue);
		
		distance = getUSDistance(USonicSensor);
		
		displayStringAt(3,20, "red: %d",redValue);
		displayStringAt(4,40, "green: %d",greenValue);
		displayStringAt(5,60, "blue: %d",blueValue);
		displayStringAt(6, 80, "distance: %d", getUSDistance(USonicSensor));

		intens = (redValue + blueValue + greenValue) / 3;
		displayStringAt(1, 10, "intensity: %d", intens);

		displayStringAt(2,20, "initItens: %d", initIntens);
		displayStringAt(3,40, "initRed: %d",initRed);
		displayStringAt(4,60, "initBlue: %d",initBlue);
		displayStringAt(5, 80, "initGreen: %d", initGreen);
		
		if (distance < 10.5 && distance > 9.5) {
			playSound(soundBeepBeep);
			sleep(2000);
		}
		
		// if current intensity is greater than initial intensity, we're too light
		if (intens >= (initIntens - 10)) {
			setMotorSpeed(lWheel, 0);
			//Set the right motor (motorB) to half power (50)
			setMotorSpeed(rWheel, topSpeed);
			} else if (intens < (initItens - 10)) { // if current intensity is darker than black,  we're too dark
			setMotorSpeed(lWheel, topSpeed);
			//Set the right motor (motorB) to half power (50)
			setMotorSpeed(rWheel, 0);
			} else { // if not too dark or too light go straight
			// if blue
			if ((blueValue > greenValue) && (blueValue > redValue)) {
				// rotate 180 degrees (turn around)
				moveMotorTarget(motorA, 200, 10);
				waitUntilMotorStop(motorA);
				
				} else if ((greenValue > blueValue) && (greenValue > redValue)) {
				// push object 10cm or wtv
				while(distance >= 4) {
					setMotorSpeed(lWheel, topSpeed);
					setMotorSpeed(rWheel, topSpeed);
				}
				
				setMotorSpeed(lWheel, 0);
				setMotorSpeed(rWheel, 0);
				
				// rotate 90 ish degrees
				moveMotorTarget(lWheel, 100, 10);
				waitUntilMotorStop(lWheel);
				
				// push 10cm
				moveMotorTarget(lWheel, 180, 10);
				moveMotorTarget(rWheel, 180, 10);
				
				// go back 10cm
				waitUntilMotorStop(lWheel);
				waitUntilMotorStop(rWheel);
				
				moveMotorTarget(lWheel, -180, 10);
				moveMotorTarget(rWheel, -180, 10);
				
				// rotate back 90 ish degrees
				waitUntilMotorStop(lWheel);
				waitUntilMotorStop(rWheel);
				moveMotorTarget(lWheel, -90, 10);

				
				} else {
				setMotorSpeed(lWheel, topSpeed);
				setMotorSpeed(rWheel, topSpeed);
			}
		}
	}
}
