#pragma config(Sensor, S1,     ColorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     USonicSensor,   sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          lWheel,        tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          rWheel,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long redValue;
long greenValue;
long blueValue;
long intens;

long initRed;
long initGreen;
long initBlue;
long initIntens;

int topSpeed = 10;
	
float distance;
int rotatedAlready = 0;

void init();
void greenAction();
void blueAction();

void init() {
	// initialize all of the first values in our robot
	sleep(2000);
	getColorRGB(ColorSensor, initRed, initGreen, initBlue);
	initIntens = (initRed + initBlue + initGreen) / 3;

	getColorRGB(ColorSensor, redValue, greenValue, blueValue);
	distance = getUSDistance(USonicSensor);
	intens = (redValue + blueValue + greenValue) / 3;
}

void greenAction() {
	// push the object out of the way
	
}

void blueAction() {
	// turn around and go back to the beginning

}

task main()
{
	init();

	//Keep looping forever
	while(true)
	{
		//If the color sensor senses the line (a dark value
		//lower than the calculated threshold of 50):

		getColorRGB(ColorSensor, redValue, greenValue, blueValue);
		eraseDisplay();
		displayStringAt(3,20, "red: %d",redValue);
		displayStringAt(4,40, "blue: %d",blueValue);
		displayStringAt(5,60, "green: %d",greenValue);
		long intens = (redValue + blueValue + greenValue) / 3;

		/*ON THE TABLE*/
		if (redValue >= 51 && redValue <= 56 &&
			blueValue >= 56 && blueValue <= 60 &&
			greenValue >= 61 && greenValue <= 63 && intens >= 56) {

			setMotorSpeed(lWheel, 0);
			setMotorSpeed(rWheel, 10);
			/*GREEN EDGE LINE || intens = 26*/ 
		} else if (redValue >= 13 && redValue <= 38 &&
			blueValue >= 27 && blueValue <= 44 &&
			greenValue >= 37 && greenValue <= 51 && 
			intens >= 26 && intens <= 45) {
			setMotorSpeed(lWheel, 10);
			setMotorSpeed(rWheel, 10);

			/*GREEN DARK || intens = 17*/
		} else if (redValue >= 5 && redValue <= 10 &&
			blueValue >= 17 && blueValue <= 25 &&
			greenValue >= 28 && greenValue <= 37 && 
			intens >= 15 && intens <= 25) {
			//moveMotorTarget(lWheel, 180, 20);
			//moveMotorTarget(rWheel, -180, -20);	
			
			waitUntilMotorStop(lWheel);
			waitUntilMotorStop(rWheel);
			//setMotorSpeed(lWheel, 80);
			//setMotorSpeed(rWheel, -80);
			
			/* BLUE DARK || intens = */
		} else if (redValue >= 4 && redValue <= 12 &&
				blueValue >= 21 && blueValue <= 31 &&
				greenValue >= 10 && greenValue <= 15 && 
			 	intens >= 10 && intens <= 19) {
				// rotate
				if (rotatedAlready == 0) {
					blueAction();
				} else {
					// rotate right to follow the line
					setMotorSpeed(lWheel, 10);
					setMotorSpeed(rWheel, 0);
				}
				/* BLUE EDGE LINE || intens = */
		} else if (redValue >= 4 && redValue <= 10 &&
				blueValue >= 21 && blueValue <= 31 &&
				greenValue >= 10 && greenValue <= 15 && 
			 	intens >= 10 && intens <= 19) {
			// do something i guess?
			// i think that this will be the black line so we can program it to turn right
		}
		
		
	}


}


