#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S4,     lightSensor,   sensorEV3_Color)
#pragma config(Motor,  motorB,          scannerMotor,  tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int light = getColorReflected(lightSensor);


	while(true) {

		int startScan = 0;
		int counter = 4000;
		if (getButtonPress(buttonEnter) == 1) {
			startScan = 1;
		}

		while(startScan == 1 && counter >= 0) {

			datalogFlush();
			datalogClose();
			if (!datalogOpen(1020, 1, false)){
				displayCenteredTextLine(4,"Unable to open datalog");
			}

			light = getColorReflected(lightSensor);
			eraseDisplay();
			displayCenteredBigTextLine(5, "%d", light);

			datalogAddValue(1, light);
			sleep(1);

			datalogClose();
			counter--;
		}
		startScan = 0;
	}
}
