#pragma config(Sensor, S2,     Light_Sensor,   sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long redValue;
long greenValue;
long blueValue;

task main()
{
	while(1)
	{
		getColorRGB(Light_Sensor, redValue, greenValue, blueValue);
		// Values returned by the color sensor typically range from 0 to 100 -Dark objects return lower values

		long intens = (redValue + greenValue + blueValue) / 3;

		if (intens >= 60) {

		}

		// if pure white, rotate left

		// if pure black, rotate right

		// if in between range, 70 - 30, move straight
			// if blue do action
			// if green do action

		displayStringAt(3,20, "%d",redValue);
		displayStringAt(4,40, "%d",greenValue);
		displayStringAt(5,60, "%d",blueValue);
	}
}
