#pragma config(Sensor, S1,     Light_Sensor,   sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Light_grade;
long redValue;
long greenValue;
long blueValue;


task main()
{
	while(1)
	{
		Light_grade = getColorReflected(Light_Sensor);// This command measures the value returned to the color sensor with its red LED turned off
		// Values returned by the color sensor typically range from 0 to 100 -Dark objects return lower values
		displayStringAt(5,100, "%d",Light_grade);
		//	writeDebugStreamLine("Colour detected: %d, %d, %d", redValue, greenValue, blueValue);
	}
}
