#pragma config(Motor,  motorA,          Left_motor,    tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

int Left_pos;
int Right_pos;
//bool t=false;
//setMotorBrakeMode(Left_motor,motorCoast);   //The motor will now Coast (does not resist movement)
setMotorBrakeMode(Left_motor,motorBrake); //The motor will now Hold  (resist movement and stay at position)

resetMotorEncoder(Left_motor);


while(1==1)
	{
		setMotorSpeed(Left_motor, 0);
		Left_pos = getMotorEncoder(Left_motor);
		displayStringAt(4,20, "%d",Left_pos);
	}

}

// Commet the above while loop and uncomment the the following while loop. The following algorithm shows an on-off period of 3 seconds.

//while(1==1)
//	{
//		setMotorSpeed(Left_motor, 40);
//		Left_pos = getMotorEncoder(Left_motor);
//		displayStringAt(4,20, "%d",Left_pos);

//		sleep(3000);

//		setMotorSpeed(Left_motor, 0);
//		Right_pos = getMotorEncoder(Left_motor);
//		displayStringAt(4,20, "%d",Left_motor);

//		sleep(8000);
//  }
//}
