#pragma config(Motor,  motorA,          LeftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

setMotorBrakeMode(LeftMotor,motorBrake);
resetMotorEncoder(LeftMotor);
int EnValue;
while(1)
{

setMotorSpeed(LeftMotor, 30);
EnValue = getMotorEncoder(LeftMotor);
displayStringAt(40, 40, "%d",EnValue);

}
}
