#pragma config(Sensor, S2,     Color_sens,     sensorEV3_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int Reflect_Int;
task main()
{
	while (1)
	{
		Reflect_Int = getColorReflected(Color_sens);
		displayStringAt(5,100, "%d",Reflect_Int);
	}

}
