#pragma config(Sensor, S1,     UltSou_Sensor,  sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float UltSou_grade;

task main()
{
	while(true)
	{
		UltSou_grade = getUSDistance(UltSou_Sensor); // Returns the value of the Ultrasonic Distance sensor

                  															 // Distance CM mode returns values in 0.1 cm increments. The sensor can detect objects up to 250.0 cm away in this mode
				displayStringAt(1,100, "%f",UltSou_grade);
			//	displayCenteredTextLine(4, "%f",UltSou_grade);
	}
}
